query 1

select distinct *   where {

?contact a <http://bittich.be/bce/Contact>;
        <http://bittich.be/bce/hasOrganization> ?hasOrg;
        <http://bittich.be/bce/hasContactType> ?hasContactType;
        <http://bittich.be/bce/value> ?value.
filter(?hasOrg=<http://bittich.be/bce/company/2283732465>)

} 

#group by ?contact ?hasOrg
#having (?hasContactType = <http://bittich.be/bce/ContactType/EMAIL>)
#order by ?hasOrg

=====

query 2



 CONSTRUCT { 
    ?hasOrg ?hasContactType ?value
 }
 WHERE {
?contact a <http://bittich.be/bce/Contact>;
        <http://bittich.be/bce/hasOrganization> ?hasOrg;
        <http://bittich.be/bce/hasContactType> ?hasContactType;
        <http://bittich.be/bce/value> ?value.
filter(?hasOrg=<http://bittich.be/bce/company/2283732465>) 
filter(?hasContactType=<http://bittich.be/bce/ContactType/TEL>) 
 }


 ===

select count(?org)   where {

?org a <http://bittich.be/bce/Organization>.

}

===


select distinct *  where {

?org a <http://www.w3.org/ns/org#Organization>.


?denomination a <http://bittich.be/bce/Denomination>;
<http://www.w3.org/ns/org#hasUnit> ?org;

 <http://xmlns.com/foaf/0.1/name> ?name.

?contact a <http://bittich.be/bce/Contact>;

<http://www.w3.org/ns/org#hasUnit> ?org;
<http://xmlns.com/foaf/0.1/homepage> ?website;
<http://xmlns.com/foaf/0.1/mbox> ?email;
<http://xmlns.com/foaf/0.1/phone> ?phone.

} limit 100



::::


select distinct *  where {

?org a <http://www.w3.org/ns/org#Organization>.


?denomination a <http://bittich.be/bce/Denomination>;
<http://www.w3.org/ns/org#hasUnit> ?org;

 <http://xmlns.com/foaf/0.1/name> ?name.

?contact a <http://bittich.be/bce/Contact>;

<http://www.w3.org/ns/org#hasUnit> ?org;
<http://xmlns.com/foaf/0.1/homepage> ?website;
<http://xmlns.com/foaf/0.1/mbox> ?email;
<http://xmlns.com/foaf/0.1/phone> ?phone.
FILTER(LANG(?name) = "" || LANGMATCHES(LANG(?name), "fr"))
} limit 1000



====


select distinct *  where {

?org a <http://www.w3.org/ns/org#Organization>;


<http://bittich.be/bce/hasJuridicalSituation> ?hasJuridicalSituation.

?hasJuridicalSituation a <http://bittich.be/bce/Code>;
<http://www.w3.org/2000/01/rdf-schema#label> ?label.


?denomination a <http://bittich.be/bce/Denomination>;
<http://www.w3.org/ns/org#hasUnit> ?org;

 <http://xmlns.com/foaf/0.1/name> ?name.

?contact a <http://bittich.be/bce/Contact>;

<http://www.w3.org/ns/org#hasUnit> ?org;
<http://xmlns.com/foaf/0.1/homepage> ?website;
<http://xmlns.com/foaf/0.1/mbox> ?email;
<http://xmlns.com/foaf/0.1/phone> ?phone.
FILTER(LANG(?name) = "" || LANGMATCHES(LANG(?name), "fr"))

FILTER(LANG(?label) = "" || LANGMATCHES(LANG(?label), "fr"))
} limit 1000